// Code generated by go-swagger; DO NOT EDIT.

package bucket

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"platform/services/storage/models"
)

// NewAddBucketParams creates a new AddBucketParams object
// no default values defined in spec.
func NewAddBucketParams() AddBucketParams {

	return AddBucketParams{}
}

// AddBucketParams contains all the bound params for the add bucket operation
// typically these are obtained from a http.Request
//
// swagger:parameters addBucket
type AddBucketParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Description of the bucket to add
	  Required: true
	  In: body
	*/
	Bucket *models.Bucket
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewAddBucketParams() beforehand.
func (o *AddBucketParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Bucket
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("bucket", "body", ""))
			} else {
				res = append(res, errors.NewParseError("bucket", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Bucket = &body
			}
		}
	} else {
		res = append(res, errors.Required("bucket", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
