// Code generated by go-swagger; DO NOT EDIT.

package bucket

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"platform/services/storage/models"
)

// DeleteBucketOKCode is the HTTP code returned for type DeleteBucketOK
const DeleteBucketOKCode int = 200

/*DeleteBucketOK Delete complete

swagger:response deleteBucketOK
*/
type DeleteBucketOK struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewDeleteBucketOK creates DeleteBucketOK with default headers values
func NewDeleteBucketOK() *DeleteBucketOK {

	return &DeleteBucketOK{}
}

// WithPayload adds the payload to the delete bucket o k response
func (o *DeleteBucketOK) WithPayload(payload *models.APIResponse) *DeleteBucketOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete bucket o k response
func (o *DeleteBucketOK) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteBucketOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteBucketBadRequestCode is the HTTP code returned for type DeleteBucketBadRequest
const DeleteBucketBadRequestCode int = 400

/*DeleteBucketBadRequest Bad request

swagger:response deleteBucketBadRequest
*/
type DeleteBucketBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewDeleteBucketBadRequest creates DeleteBucketBadRequest with default headers values
func NewDeleteBucketBadRequest() *DeleteBucketBadRequest {

	return &DeleteBucketBadRequest{}
}

// WithPayload adds the payload to the delete bucket bad request response
func (o *DeleteBucketBadRequest) WithPayload(payload *models.APIResponse) *DeleteBucketBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete bucket bad request response
func (o *DeleteBucketBadRequest) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteBucketBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteBucketNotFoundCode is the HTTP code returned for type DeleteBucketNotFound
const DeleteBucketNotFoundCode int = 404

/*DeleteBucketNotFound Not found

swagger:response deleteBucketNotFound
*/
type DeleteBucketNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewDeleteBucketNotFound creates DeleteBucketNotFound with default headers values
func NewDeleteBucketNotFound() *DeleteBucketNotFound {

	return &DeleteBucketNotFound{}
}

// WithPayload adds the payload to the delete bucket not found response
func (o *DeleteBucketNotFound) WithPayload(payload *models.APIResponse) *DeleteBucketNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete bucket not found response
func (o *DeleteBucketNotFound) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteBucketNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteBucketInternalServerErrorCode is the HTTP code returned for type DeleteBucketInternalServerError
const DeleteBucketInternalServerErrorCode int = 500

/*DeleteBucketInternalServerError Internal error

swagger:response deleteBucketInternalServerError
*/
type DeleteBucketInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewDeleteBucketInternalServerError creates DeleteBucketInternalServerError with default headers values
func NewDeleteBucketInternalServerError() *DeleteBucketInternalServerError {

	return &DeleteBucketInternalServerError{}
}

// WithPayload adds the payload to the delete bucket internal server error response
func (o *DeleteBucketInternalServerError) WithPayload(payload *models.APIResponse) *DeleteBucketInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete bucket internal server error response
func (o *DeleteBucketInternalServerError) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteBucketInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
