// Code generated by go-swagger; DO NOT EDIT.

package bucket

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"platform/services/storage/models"
)

// GetBucketsOKCode is the HTTP code returned for type GetBucketsOK
const GetBucketsOKCode int = 200

/*GetBucketsOK Ok

swagger:response getBucketsOK
*/
type GetBucketsOK struct {

	/*
	  In: Body
	*/
	Payload models.BucketList `json:"body,omitempty"`
}

// NewGetBucketsOK creates GetBucketsOK with default headers values
func NewGetBucketsOK() *GetBucketsOK {

	return &GetBucketsOK{}
}

// WithPayload adds the payload to the get buckets o k response
func (o *GetBucketsOK) WithPayload(payload models.BucketList) *GetBucketsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get buckets o k response
func (o *GetBucketsOK) SetPayload(payload models.BucketList) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBucketsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.BucketList{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetBucketsBadRequestCode is the HTTP code returned for type GetBucketsBadRequest
const GetBucketsBadRequestCode int = 400

/*GetBucketsBadRequest Bad request

swagger:response getBucketsBadRequest
*/
type GetBucketsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetBucketsBadRequest creates GetBucketsBadRequest with default headers values
func NewGetBucketsBadRequest() *GetBucketsBadRequest {

	return &GetBucketsBadRequest{}
}

// WithPayload adds the payload to the get buckets bad request response
func (o *GetBucketsBadRequest) WithPayload(payload *models.APIResponse) *GetBucketsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get buckets bad request response
func (o *GetBucketsBadRequest) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBucketsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBucketsNotFoundCode is the HTTP code returned for type GetBucketsNotFound
const GetBucketsNotFoundCode int = 404

/*GetBucketsNotFound Not found

swagger:response getBucketsNotFound
*/
type GetBucketsNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetBucketsNotFound creates GetBucketsNotFound with default headers values
func NewGetBucketsNotFound() *GetBucketsNotFound {

	return &GetBucketsNotFound{}
}

// WithPayload adds the payload to the get buckets not found response
func (o *GetBucketsNotFound) WithPayload(payload *models.APIResponse) *GetBucketsNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get buckets not found response
func (o *GetBucketsNotFound) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBucketsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBucketsInternalServerErrorCode is the HTTP code returned for type GetBucketsInternalServerError
const GetBucketsInternalServerErrorCode int = 500

/*GetBucketsInternalServerError Internal error

swagger:response getBucketsInternalServerError
*/
type GetBucketsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetBucketsInternalServerError creates GetBucketsInternalServerError with default headers values
func NewGetBucketsInternalServerError() *GetBucketsInternalServerError {

	return &GetBucketsInternalServerError{}
}

// WithPayload adds the payload to the get buckets internal server error response
func (o *GetBucketsInternalServerError) WithPayload(payload *models.APIResponse) *GetBucketsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get buckets internal server error response
func (o *GetBucketsInternalServerError) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBucketsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
