// Code generated by go-swagger; DO NOT EDIT.

package table

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewDeleteTableParams creates a new DeleteTableParams object
// no default values defined in spec.
func NewDeleteTableParams() DeleteTableParams {

	return DeleteTableParams{}
}

// DeleteTableParams contains all the bound params for the delete table operation
// typically these are obtained from a http.Request
//
// swagger:parameters deleteTable
type DeleteTableParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Name of keyspace
	  Required: true
	  In: path
	*/
	KeyspaceName string
	/*Name of table to delete
	  Required: true
	  In: path
	*/
	TableName string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeleteTableParams() beforehand.
func (o *DeleteTableParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rKeyspaceName, rhkKeyspaceName, _ := route.Params.GetOK("keyspaceName")
	if err := o.bindKeyspaceName(rKeyspaceName, rhkKeyspaceName, route.Formats); err != nil {
		res = append(res, err)
	}

	rTableName, rhkTableName, _ := route.Params.GetOK("tableName")
	if err := o.bindTableName(rTableName, rhkTableName, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindKeyspaceName binds and validates parameter KeyspaceName from path.
func (o *DeleteTableParams) bindKeyspaceName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.KeyspaceName = raw

	return nil
}

// bindTableName binds and validates parameter TableName from path.
func (o *DeleteTableParams) bindTableName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.TableName = raw

	return nil
}
