// Code generated by go-swagger; DO NOT EDIT.

package table

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"platform/services/docdb/models"
)

// GetTableHandlerFunc turns a function with the right signature into a get table handler
type GetTableHandlerFunc func(GetTableParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTableHandlerFunc) Handle(params GetTableParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetTableHandler interface for that can handle valid get table params
type GetTableHandler interface {
	Handle(GetTableParams, *models.Principal) middleware.Responder
}

// NewGetTable creates a new http.Handler for the get table operation
func NewGetTable(ctx *middleware.Context, handler GetTableHandler) *GetTable {
	return &GetTable{Context: ctx, Handler: handler}
}

/*GetTable swagger:route GET /{keyspaceName}/table/{tableName} table getTable

Find a table from name

Returns a single table

*/
type GetTable struct {
	Context *middleware.Context
	Handler GetTableHandler
}

func (o *GetTable) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetTableParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
