// Code generated by go-swagger; DO NOT EDIT.

package table

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"platform/services/docdb/models"
)

// GetTablesHandlerFunc turns a function with the right signature into a get tables handler
type GetTablesHandlerFunc func(GetTablesParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTablesHandlerFunc) Handle(params GetTablesParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetTablesHandler interface for that can handle valid get tables params
type GetTablesHandler interface {
	Handle(GetTablesParams, *models.Principal) middleware.Responder
}

// NewGetTables creates a new http.Handler for the get tables operation
func NewGetTables(ctx *middleware.Context, handler GetTablesHandler) *GetTables {
	return &GetTables{Context: ctx, Handler: handler}
}

/*GetTables swagger:route GET /{keyspaceName}/tables table getTables

Lists all tables in a keyspace

Returns the list of table names in the keyspace

*/
type GetTables struct {
	Context *middleware.Context
	Handler GetTablesHandler
}

func (o *GetTables) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetTablesParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
