// Code generated by go-swagger; DO NOT EDIT.

package table

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"platform/services/docdb/models"
)

// UpdateTableHandlerFunc turns a function with the right signature into a update table handler
type UpdateTableHandlerFunc func(UpdateTableParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateTableHandlerFunc) Handle(params UpdateTableParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// UpdateTableHandler interface for that can handle valid update table params
type UpdateTableHandler interface {
	Handle(UpdateTableParams, *models.Principal) middleware.Responder
}

// NewUpdateTable creates a new http.Handler for the update table operation
func NewUpdateTable(ctx *middleware.Context, handler UpdateTableHandler) *UpdateTable {
	return &UpdateTable{Context: ctx, Handler: handler}
}

/*UpdateTable swagger:route PUT /{keyspaceName}/table table updateTable

Updates a table in the store (table name cannot be updated).

Update the table by either adding or removing column, or changing options

*/
type UpdateTable struct {
	Context *middleware.Context
	Handler UpdateTableHandler
}

func (o *UpdateTable) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateTableParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
