// Code generated by go-swagger; DO NOT EDIT.

package table

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"

	"platform/services/docdb/models"
)

// NewUpdateTableParams creates a new UpdateTableParams object
// no default values defined in spec.
func NewUpdateTableParams() UpdateTableParams {

	return UpdateTableParams{}
}

// UpdateTableParams contains all the bound params for the update table operation
// typically these are obtained from a http.Request
//
// swagger:parameters updateTable
type UpdateTableParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Name of keyspace
	  Required: true
	  In: path
	*/
	KeyspaceName string
	/*Table update
	  Required: true
	  In: body
	*/
	TableUpdate *models.TableUpdate
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewUpdateTableParams() beforehand.
func (o *UpdateTableParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rKeyspaceName, rhkKeyspaceName, _ := route.Params.GetOK("keyspaceName")
	if err := o.bindKeyspaceName(rKeyspaceName, rhkKeyspaceName, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.TableUpdate
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("tableUpdate", "body", ""))
			} else {
				res = append(res, errors.NewParseError("tableUpdate", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.TableUpdate = &body
			}
		}
	} else {
		res = append(res, errors.Required("tableUpdate", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindKeyspaceName binds and validates parameter KeyspaceName from path.
func (o *UpdateTableParams) bindKeyspaceName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.KeyspaceName = raw

	return nil
}
