// Code generated by go-swagger; DO NOT EDIT.

package objectinfo

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag"
)

// GetObjectInfoURL generates an URL for the get object info operation
type GetObjectInfoURL struct {
	BucketName string

	Isolation  *bool
	ObjectName string
	Owner      *string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetObjectInfoURL) WithBasePath(bp string) *GetObjectInfoURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetObjectInfoURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *GetObjectInfoURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/{bucketName}/objectinfo"

	bucketName := o.BucketName
	if bucketName != "" {
		_path = strings.Replace(_path, "{bucketName}", bucketName, -1)
	} else {
		return nil, errors.New("bucketName is required on GetObjectInfoURL")
	}

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api/v0-alpha1"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var isolationQ string
	if o.Isolation != nil {
		isolationQ = swag.FormatBool(*o.Isolation)
	}
	if isolationQ != "" {
		qs.Set("isolation", isolationQ)
	}

	objectNameQ := o.ObjectName
	if objectNameQ != "" {
		qs.Set("objectName", objectNameQ)
	}

	var ownerQ string
	if o.Owner != nil {
		ownerQ = *o.Owner
	}
	if ownerQ != "" {
		qs.Set("owner", ownerQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *GetObjectInfoURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *GetObjectInfoURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *GetObjectInfoURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on GetObjectInfoURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on GetObjectInfoURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *GetObjectInfoURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
