// Code generated by go-swagger; DO NOT EDIT.

package file

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"platform/services/storage/models"
)

// AddFileHandlerFunc turns a function with the right signature into a add file handler
type AddFileHandlerFunc func(AddFileParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn AddFileHandlerFunc) Handle(params AddFileParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// AddFileHandler interface for that can handle valid add file params
type AddFileHandler interface {
	Handle(AddFileParams, *models.Principal) middleware.Responder
}

// NewAddFile creates a new http.Handler for the add file operation
func NewAddFile(ctx *middleware.Context, handler AddFileHandler) *AddFile {
	return &AddFile{Context: ctx, Handler: handler}
}

/*AddFile swagger:route POST /{bucketName}/file file addFile

Add a new object into a bucket

*/
type AddFile struct {
	Context *middleware.Context
	Handler AddFileHandler
}

func (o *AddFile) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAddFileParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
