// Code generated by go-swagger; DO NOT EDIT.

package query

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"platform/services/docdb/models"
)

// DeleteQueryHandlerFunc turns a function with the right signature into a delete query handler
type DeleteQueryHandlerFunc func(DeleteQueryParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteQueryHandlerFunc) Handle(params DeleteQueryParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// DeleteQueryHandler interface for that can handle valid delete query params
type DeleteQueryHandler interface {
	Handle(DeleteQueryParams, *models.Principal) middleware.Responder
}

// NewDeleteQuery creates a new http.Handler for the delete query operation
func NewDeleteQuery(ctx *middleware.Context, handler DeleteQueryHandler) *DeleteQuery {
	return &DeleteQuery{Context: ctx, Handler: handler}
}

/*DeleteQuery swagger:route DELETE /{keyspaceName}/{tableName}/query query deleteQuery

Deletes a selection of entities

*/
type DeleteQuery struct {
	Context *middleware.Context
	Handler DeleteQueryHandler
}

func (o *DeleteQuery) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteQueryParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
