// Code generated by go-swagger; DO NOT EDIT.

package document

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"platform/services/docdb/models"
)

// GetDocumentHandlerFunc turns a function with the right signature into a get document handler
type GetDocumentHandlerFunc func(GetDocumentParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDocumentHandlerFunc) Handle(params GetDocumentParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetDocumentHandler interface for that can handle valid get document params
type GetDocumentHandler interface {
	Handle(GetDocumentParams, *models.Principal) middleware.Responder
}

// NewGetDocument creates a new http.Handler for the get document operation
func NewGetDocument(ctx *middleware.Context, handler GetDocumentHandler) *GetDocument {
	return &GetDocument{Context: ctx, Handler: handler}
}

/*GetDocument swagger:route GET /{keyspaceName}/{tableName}/document document getDocument

Find a document from partition & clustering keys

Returns a single entity

*/
type GetDocument struct {
	Context *middleware.Context
	Handler GetDocumentHandler
}

func (o *GetDocument) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetDocumentParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
