// Code generated by go-swagger; DO NOT EDIT.

package document

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"platform/services/docdb/models"
)

// GetDocumentOKCode is the HTTP code returned for type GetDocumentOK
const GetDocumentOKCode int = 200

/*GetDocumentOK successful operation

swagger:response getDocumentOK
*/
type GetDocumentOK struct {

	/*
	  In: Body
	*/
	Payload models.Document `json:"body,omitempty"`
}

// NewGetDocumentOK creates GetDocumentOK with default headers values
func NewGetDocumentOK() *GetDocumentOK {

	return &GetDocumentOK{}
}

// WithPayload adds the payload to the get document o k response
func (o *GetDocumentOK) WithPayload(payload models.Document) *GetDocumentOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get document o k response
func (o *GetDocumentOK) SetPayload(payload models.Document) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDocumentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetDocumentBadRequestCode is the HTTP code returned for type GetDocumentBadRequest
const GetDocumentBadRequestCode int = 400

/*GetDocumentBadRequest Bad request

swagger:response getDocumentBadRequest
*/
type GetDocumentBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetDocumentBadRequest creates GetDocumentBadRequest with default headers values
func NewGetDocumentBadRequest() *GetDocumentBadRequest {

	return &GetDocumentBadRequest{}
}

// WithPayload adds the payload to the get document bad request response
func (o *GetDocumentBadRequest) WithPayload(payload *models.APIResponse) *GetDocumentBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get document bad request response
func (o *GetDocumentBadRequest) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDocumentBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetDocumentUnauthorizedCode is the HTTP code returned for type GetDocumentUnauthorized
const GetDocumentUnauthorizedCode int = 401

/*GetDocumentUnauthorized Unauthorized

swagger:response getDocumentUnauthorized
*/
type GetDocumentUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetDocumentUnauthorized creates GetDocumentUnauthorized with default headers values
func NewGetDocumentUnauthorized() *GetDocumentUnauthorized {

	return &GetDocumentUnauthorized{}
}

// WithPayload adds the payload to the get document unauthorized response
func (o *GetDocumentUnauthorized) WithPayload(payload *models.APIResponse) *GetDocumentUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get document unauthorized response
func (o *GetDocumentUnauthorized) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDocumentUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetDocumentNotFoundCode is the HTTP code returned for type GetDocumentNotFound
const GetDocumentNotFoundCode int = 404

/*GetDocumentNotFound Not found

swagger:response getDocumentNotFound
*/
type GetDocumentNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetDocumentNotFound creates GetDocumentNotFound with default headers values
func NewGetDocumentNotFound() *GetDocumentNotFound {

	return &GetDocumentNotFound{}
}

// WithPayload adds the payload to the get document not found response
func (o *GetDocumentNotFound) WithPayload(payload *models.APIResponse) *GetDocumentNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get document not found response
func (o *GetDocumentNotFound) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDocumentNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetDocumentInternalServerErrorCode is the HTTP code returned for type GetDocumentInternalServerError
const GetDocumentInternalServerErrorCode int = 500

/*GetDocumentInternalServerError Internal error

swagger:response getDocumentInternalServerError
*/
type GetDocumentInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetDocumentInternalServerError creates GetDocumentInternalServerError with default headers values
func NewGetDocumentInternalServerError() *GetDocumentInternalServerError {

	return &GetDocumentInternalServerError{}
}

// WithPayload adds the payload to the get document internal server error response
func (o *GetDocumentInternalServerError) WithPayload(payload *models.APIResponse) *GetDocumentInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get document internal server error response
func (o *GetDocumentInternalServerError) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDocumentInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
