// Code generated by go-swagger; DO NOT EDIT.

package document

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"

	"platform/services/docdb/models"
)

// NewUpdateDocumentParams creates a new UpdateDocumentParams object
// with the default values initialized.
func NewUpdateDocumentParams() UpdateDocumentParams {

	var (
		// initialize parameters with default values

		ownerDefault = string("")
	)

	return UpdateDocumentParams{
		Owner: &ownerDefault,
	}
}

// UpdateDocumentParams contains all the bound params for the update document operation
// typically these are obtained from a http.Request
//
// swagger:parameters updateDocument
type UpdateDocumentParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Updated document
	  Required: true
	  In: body
	*/
	Document models.Document
	/*Name of keyspace to use
	  Required: true
	  In: path
	*/
	KeyspaceName string
	/*Which owner does the document belong to ? Defaults to current user. Indicate a group path to act as a group (e.g.: /youwol-users/subgroup)
	  In: query
	  Default: ""
	*/
	Owner *string
	/*Name of table to return
	  Required: true
	  In: path
	*/
	TableName string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewUpdateDocumentParams() beforehand.
func (o *UpdateDocumentParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Document
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("document", "body", ""))
			} else {
				res = append(res, errors.NewParseError("document", "body", "", err))
			}
		} else {
			// no validation on generic interface
			o.Document = body
		}
	} else {
		res = append(res, errors.Required("document", "body", ""))
	}
	rKeyspaceName, rhkKeyspaceName, _ := route.Params.GetOK("keyspaceName")
	if err := o.bindKeyspaceName(rKeyspaceName, rhkKeyspaceName, route.Formats); err != nil {
		res = append(res, err)
	}

	qOwner, qhkOwner, _ := qs.GetOK("owner")
	if err := o.bindOwner(qOwner, qhkOwner, route.Formats); err != nil {
		res = append(res, err)
	}

	rTableName, rhkTableName, _ := route.Params.GetOK("tableName")
	if err := o.bindTableName(rTableName, rhkTableName, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindKeyspaceName binds and validates parameter KeyspaceName from path.
func (o *UpdateDocumentParams) bindKeyspaceName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.KeyspaceName = raw

	return nil
}

// bindOwner binds and validates parameter Owner from query.
func (o *UpdateDocumentParams) bindOwner(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewUpdateDocumentParams()
		return nil
	}

	o.Owner = &raw

	return nil
}

// bindTableName binds and validates parameter TableName from path.
func (o *UpdateDocumentParams) bindTableName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.TableName = raw

	return nil
}
