apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "storage.fullname" . }}
  labels:
    {{- include "storage.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "storage.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "storage.selectorLabels" . | nindent 8 }}
      annotations:
        releaseTime: {{ dateInZone "2006-01-02 15:04:05Z" (now) "UTC"| quote }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "storage.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: MINIO_HOST_PORT
              value: {{ .Values.config.environment.MINIO_HOST_PORT }}
            - name: MINIO_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: minio_access_key
            - name: MINIO_ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  name: minio-app-secret
                  key: app-secret-key
            - name: KEYCLOAK_HOST
              value: {{ .Values.keycloak.host  }}
            - name: OPENID_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: openid_client_id
            - name: OPENID_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: openid-app-secret
                  key: openid_client_secret
            - name: REDIS_HOST_PORT
              value: redis-master.infra.svc.cluster.local:6379
            - name: ENVIRONMENT
              value: {{ .Release.Namespace }}
          livenessProbe:
            httpGet:
              path: /alive
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 2
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 2
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
