// Code generated by go-swagger; DO NOT EDIT.

package objects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"platform/services/storage/models"
)

// DeleteObjectsHandlerFunc turns a function with the right signature into a delete objects handler
type DeleteObjectsHandlerFunc func(DeleteObjectsParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteObjectsHandlerFunc) Handle(params DeleteObjectsParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// DeleteObjectsHandler interface for that can handle valid delete objects params
type DeleteObjectsHandler interface {
	Handle(DeleteObjectsParams, *models.Principal) middleware.Responder
}

// NewDeleteObjects creates a new http.Handler for the delete objects operation
func NewDeleteObjects(ctx *middleware.Context, handler DeleteObjectsHandler) *DeleteObjects {
	return &DeleteObjects{Context: ctx, Handler: handler}
}

/*DeleteObjects swagger:route DELETE /{bucketName}/objects objects deleteObjects

Delete a list of objects in a bucket

*/
type DeleteObjects struct {
	Context *middleware.Context
	Handler DeleteObjectsHandler
}

func (o *DeleteObjects) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteObjectsParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
