// Code generated by go-swagger; DO NOT EDIT.

package objects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag"
)

// GetObjectsURL generates an URL for the get objects operation
type GetObjectsURL struct {
	BucketName string

	Isolation *bool
	Owner     *string
	Prefix    *string
	Recursive *bool

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetObjectsURL) WithBasePath(bp string) *GetObjectsURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetObjectsURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *GetObjectsURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/{bucketName}/objects"

	bucketName := o.BucketName
	if bucketName != "" {
		_path = strings.Replace(_path, "{bucketName}", bucketName, -1)
	} else {
		return nil, errors.New("bucketName is required on GetObjectsURL")
	}

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api/v0-alpha1"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var isolationQ string
	if o.Isolation != nil {
		isolationQ = swag.FormatBool(*o.Isolation)
	}
	if isolationQ != "" {
		qs.Set("isolation", isolationQ)
	}

	var ownerQ string
	if o.Owner != nil {
		ownerQ = *o.Owner
	}
	if ownerQ != "" {
		qs.Set("owner", ownerQ)
	}

	var prefixQ string
	if o.Prefix != nil {
		prefixQ = *o.Prefix
	}
	if prefixQ != "" {
		qs.Set("prefix", prefixQ)
	}

	var recursiveQ string
	if o.Recursive != nil {
		recursiveQ = swag.FormatBool(*o.Recursive)
	}
	if recursiveQ != "" {
		qs.Set("recursive", recursiveQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *GetObjectsURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *GetObjectsURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *GetObjectsURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on GetObjectsURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on GetObjectsURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *GetObjectsURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
