// Code generated by go-swagger; DO NOT EDIT.

package objects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"platform/services/storage/models"
)

// GetObjectsHandlerFunc turns a function with the right signature into a get objects handler
type GetObjectsHandlerFunc func(GetObjectsParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetObjectsHandlerFunc) Handle(params GetObjectsParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetObjectsHandler interface for that can handle valid get objects params
type GetObjectsHandler interface {
	Handle(GetObjectsParams, *models.Principal) middleware.Responder
}

// NewGetObjects creates a new http.Handler for the get objects operation
func NewGetObjects(ctx *middleware.Context, handler GetObjectsHandler) *GetObjects {
	return &GetObjects{Context: ctx, Handler: handler}
}

/*GetObjects swagger:route GET /{bucketName}/objects objects getObjects

Retrieve a list of object information in a bucket

*/
type GetObjects struct {
	Context *middleware.Context
	Handler GetObjectsHandler
}

func (o *GetObjects) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetObjectsParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
