// Code generated by go-swagger; DO NOT EDIT.

package objects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"platform/services/storage/models"
)

// GetObjectsOKCode is the HTTP code returned for type GetObjectsOK
const GetObjectsOKCode int = 200

/*GetObjectsOK Ok

swagger:response getObjectsOK
*/
type GetObjectsOK struct {

	/*
	  In: Body
	*/
	Payload models.ObjectInfoList `json:"body,omitempty"`
}

// NewGetObjectsOK creates GetObjectsOK with default headers values
func NewGetObjectsOK() *GetObjectsOK {

	return &GetObjectsOK{}
}

// WithPayload adds the payload to the get objects o k response
func (o *GetObjectsOK) WithPayload(payload models.ObjectInfoList) *GetObjectsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get objects o k response
func (o *GetObjectsOK) SetPayload(payload models.ObjectInfoList) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetObjectsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.ObjectInfoList{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetObjectsBadRequestCode is the HTTP code returned for type GetObjectsBadRequest
const GetObjectsBadRequestCode int = 400

/*GetObjectsBadRequest Bad request

swagger:response getObjectsBadRequest
*/
type GetObjectsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetObjectsBadRequest creates GetObjectsBadRequest with default headers values
func NewGetObjectsBadRequest() *GetObjectsBadRequest {

	return &GetObjectsBadRequest{}
}

// WithPayload adds the payload to the get objects bad request response
func (o *GetObjectsBadRequest) WithPayload(payload *models.APIResponse) *GetObjectsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get objects bad request response
func (o *GetObjectsBadRequest) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetObjectsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetObjectsNotFoundCode is the HTTP code returned for type GetObjectsNotFound
const GetObjectsNotFoundCode int = 404

/*GetObjectsNotFound Not found

swagger:response getObjectsNotFound
*/
type GetObjectsNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetObjectsNotFound creates GetObjectsNotFound with default headers values
func NewGetObjectsNotFound() *GetObjectsNotFound {

	return &GetObjectsNotFound{}
}

// WithPayload adds the payload to the get objects not found response
func (o *GetObjectsNotFound) WithPayload(payload *models.APIResponse) *GetObjectsNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get objects not found response
func (o *GetObjectsNotFound) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetObjectsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetObjectsInternalServerErrorCode is the HTTP code returned for type GetObjectsInternalServerError
const GetObjectsInternalServerErrorCode int = 500

/*GetObjectsInternalServerError Internal error

swagger:response getObjectsInternalServerError
*/
type GetObjectsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetObjectsInternalServerError creates GetObjectsInternalServerError with default headers values
func NewGetObjectsInternalServerError() *GetObjectsInternalServerError {

	return &GetObjectsInternalServerError{}
}

// WithPayload adds the payload to the get objects internal server error response
func (o *GetObjectsInternalServerError) WithPayload(payload *models.APIResponse) *GetObjectsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get objects internal server error response
func (o *GetObjectsInternalServerError) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetObjectsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
