{{- if .Values.mappings.enabled -}}
{{- range $key, $value := .Values.mappings.targetHosts }}
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: {{ template "docdb.fullname" $ }}-{{ $key }}
  namespace: {{ $.Release.Namespace }}
spec:
  host: {{ $value }}
  prefix: /api/docdb/v0-alpha1/
  rewrite: /api/v0-alpha1/
  service: '{{ template "docdb.fullname" $ }}:80'
  timeout_ms: 30000
  retry_policy:
    retry_on: "5xx"
    num_retries: 4
---
{{- end }}
{{- end }}
{{- if .Values.ingress.enabled -}}
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: {{ include "docdb.fullname" . }}
  namespace: {{ $.Release.Namespace }}
upstream:
  slots: 10
  hash_on: none
  hash_fallback: none
  healthchecks:
    threshold: 25
    active:
      healthy:
        http_statuses:
        - 200
        interval: 10
      http_path: "/ready"
      timeout: 1
proxy:
  protocol: http
  connect_timeout: 60000
  path: /api/v0-alpha1
  retries: 10
  read_timeout: 10000
  write_timeout: 10000
route:
  regex_priority: 0
  strip_path: true
  preserve_host: true
  protocols:
  - https
{{- end }}