// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DeleteStatement DELETE query description. @see: https://docs.scylladb.com/getting-started/dml/#delete-statement
//
// swagger:model DeleteStatement
type DeleteStatement struct {

	// condition
	Condition []*QueryRelation `json:"condition"`

	// simple selection
	SimpleSelection []string `json:"simple_selection"`

	// timestamp
	// Format: date-time
	Timestamp strfmt.DateTime `json:"timestamp,omitempty"`

	// where clause
	WhereClause []*QueryRelation `json:"where_clause"`
}

// Validate validates this delete statement
func (m *DeleteStatement) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCondition(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTimestamp(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateWhereClause(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DeleteStatement) validateCondition(formats strfmt.Registry) error {

	if swag.IsZero(m.Condition) { // not required
		return nil
	}

	for i := 0; i < len(m.Condition); i++ {
		if swag.IsZero(m.Condition[i]) { // not required
			continue
		}

		if m.Condition[i] != nil {
			if err := m.Condition[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("condition" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *DeleteStatement) validateTimestamp(formats strfmt.Registry) error {

	if swag.IsZero(m.Timestamp) { // not required
		return nil
	}

	if err := validate.FormatOf("timestamp", "body", "date-time", m.Timestamp.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *DeleteStatement) validateWhereClause(formats strfmt.Registry) error {

	if swag.IsZero(m.WhereClause) { // not required
		return nil
	}

	for i := 0; i < len(m.WhereClause); i++ {
		if swag.IsZero(m.WhereClause[i]) { // not required
			continue
		}

		if m.WhereClause[i] != nil {
			if err := m.WhereClause[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("where_clause" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *DeleteStatement) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeleteStatement) UnmarshalBinary(b []byte) error {
	var res DeleteStatement
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
