// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// EntityID The entity ID is the primary key of a document (combination of all primary columns values)
//
// swagger:model EntityId
type EntityID interface{}
