// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Query query
//
// swagger:model Query
type Query struct {

	// ordering clause
	OrderingClause []*Order `json:"ordering_clause"`

	// where clause
	WhereClause []*QueryRelation `json:"where_clause"`
}

// Validate validates this query
func (m *Query) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOrderingClause(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateWhereClause(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Query) validateOrderingClause(formats strfmt.Registry) error {

	if swag.IsZero(m.OrderingClause) { // not required
		return nil
	}

	for i := 0; i < len(m.OrderingClause); i++ {
		if swag.IsZero(m.OrderingClause[i]) { // not required
			continue
		}

		if m.OrderingClause[i] != nil {
			if err := m.OrderingClause[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("ordering_clause" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *Query) validateWhereClause(formats strfmt.Registry) error {

	if swag.IsZero(m.WhereClause) { // not required
		return nil
	}

	for i := 0; i < len(m.WhereClause); i++ {
		if swag.IsZero(m.WhereClause[i]) { // not required
			continue
		}

		if m.WhereClause[i] != nil {
			if err := m.WhereClause[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("where_clause" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Query) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Query) UnmarshalBinary(b []byte) error {
	var res Query
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
