// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Storage API
//
//  Schemes:
//    http
//  Host: storage
//  BasePath: /api/v0-alpha1
//  Version: 0.0.4
//  License: MIT http://www.youwol.com
//  Contact: <yguyomar@youwol.com>
//
//  Consumes:
//    - application/json
//    - multipart/form-data
//
//  Produces:
//    - application/octet-stream
//    - application/json
//
// swagger:meta
package restapi
