// Code generated by go-swagger; DO NOT EDIT.

package keyspace

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"platform/services/docdb/models"
)

// NewAddKeyspaceParams creates a new AddKeyspaceParams object
// no default values defined in spec.
func NewAddKeyspaceParams() AddKeyspaceParams {

	return AddKeyspaceParams{}
}

// AddKeyspaceParams contains all the bound params for the add keyspace operation
// typically these are obtained from a http.Request
//
// swagger:parameters addKeyspace
type AddKeyspaceParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Keyspace to be added
	  Required: true
	  In: body
	*/
	Keyspace *models.Keyspace
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewAddKeyspaceParams() beforehand.
func (o *AddKeyspaceParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Keyspace
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("keyspace", "body", ""))
			} else {
				res = append(res, errors.NewParseError("keyspace", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Keyspace = &body
			}
		}
	} else {
		res = append(res, errors.Required("keyspace", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
