// Code generated by go-swagger; DO NOT EDIT.

package keyspace

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewDeleteKeyspaceParams creates a new DeleteKeyspaceParams object
// no default values defined in spec.
func NewDeleteKeyspaceParams() DeleteKeyspaceParams {

	return DeleteKeyspaceParams{}
}

// DeleteKeyspaceParams contains all the bound params for the delete keyspace operation
// typically these are obtained from a http.Request
//
// swagger:parameters deleteKeyspace
type DeleteKeyspaceParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	KeyspaceName string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeleteKeyspaceParams() beforehand.
func (o *DeleteKeyspaceParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rKeyspaceName, rhkKeyspaceName, _ := route.Params.GetOK("keyspaceName")
	if err := o.bindKeyspaceName(rKeyspaceName, rhkKeyspaceName, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindKeyspaceName binds and validates parameter KeyspaceName from path.
func (o *DeleteKeyspaceParams) bindKeyspaceName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.KeyspaceName = raw

	return nil
}
