// Code generated by go-swagger; DO NOT EDIT.

package keyspace

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"platform/services/docdb/models"
)

// DeleteKeyspaceHandlerFunc turns a function with the right signature into a delete keyspace handler
type DeleteKeyspaceHandlerFunc func(DeleteKeyspaceParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteKeyspaceHandlerFunc) Handle(params DeleteKeyspaceParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// DeleteKeyspaceHandler interface for that can handle valid delete keyspace params
type DeleteKeyspaceHandler interface {
	Handle(DeleteKeyspaceParams, *models.Principal) middleware.Responder
}

// NewDeleteKeyspace creates a new http.Handler for the delete keyspace operation
func NewDeleteKeyspace(ctx *middleware.Context, handler DeleteKeyspaceHandler) *DeleteKeyspace {
	return &DeleteKeyspace{Context: ctx, Handler: handler}
}

/*DeleteKeyspace swagger:route DELETE /keyspace/{keyspaceName} keyspace deleteKeyspace

Deletes a keyspace

*/
type DeleteKeyspace struct {
	Context *middleware.Context
	Handler DeleteKeyspaceHandler
}

func (o *DeleteKeyspace) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteKeyspaceParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
