// Code generated by go-swagger; DO NOT EDIT.

package keyspace

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"platform/services/docdb/models"
)

// GetKeyspacesHandlerFunc turns a function with the right signature into a get keyspaces handler
type GetKeyspacesHandlerFunc func(GetKeyspacesParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetKeyspacesHandlerFunc) Handle(params GetKeyspacesParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetKeyspacesHandler interface for that can handle valid get keyspaces params
type GetKeyspacesHandler interface {
	Handle(GetKeyspacesParams, *models.Principal) middleware.Responder
}

// NewGetKeyspaces creates a new http.Handler for the get keyspaces operation
func NewGetKeyspaces(ctx *middleware.Context, handler GetKeyspacesHandler) *GetKeyspaces {
	return &GetKeyspaces{Context: ctx, Handler: handler}
}

/*GetKeyspaces swagger:route GET /keyspaces keyspace getKeyspaces

Lists all keyspaces

Returns a list of keyspaces names

*/
type GetKeyspaces struct {
	Context *middleware.Context
	Handler GetKeyspacesHandler
}

func (o *GetKeyspaces) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetKeyspacesParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
