// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"platform/services/storage/models"
	"platform/services/storage/restapi/operations/bucket"
	"platform/services/storage/restapi/operations/file"
	"platform/services/storage/restapi/operations/object"
	"platform/services/storage/restapi/operations/objectinfo"
	"platform/services/storage/restapi/operations/objects"
)

// NewStorageAPI creates a new Storage instance
func NewStorageAPI(spec *loads.Document) *StorageAPI {
	return &StorageAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		JSONConsumer:          runtime.JSONConsumer(),
		MultipartformConsumer: runtime.DiscardConsumer,

		BinProducer:  runtime.ByteStreamProducer(),
		JSONProducer: runtime.JSONProducer(),

		BucketAddBucketHandler: bucket.AddBucketHandlerFunc(func(params bucket.AddBucketParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation bucket.AddBucket has not yet been implemented")
		}),
		FileAddFileHandler: file.AddFileHandlerFunc(func(params file.AddFileParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation file.AddFile has not yet been implemented")
		}),
		ObjectAddObjectHandler: object.AddObjectHandlerFunc(func(params object.AddObjectParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation object.AddObject has not yet been implemented")
		}),
		BucketDeleteBucketHandler: bucket.DeleteBucketHandlerFunc(func(params bucket.DeleteBucketParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation bucket.DeleteBucket has not yet been implemented")
		}),
		ObjectDeleteObjectHandler: object.DeleteObjectHandlerFunc(func(params object.DeleteObjectParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation object.DeleteObject has not yet been implemented")
		}),
		ObjectsDeleteObjectsHandler: objects.DeleteObjectsHandlerFunc(func(params objects.DeleteObjectsParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation objects.DeleteObjects has not yet been implemented")
		}),
		BucketGetBucketsHandler: bucket.GetBucketsHandlerFunc(func(params bucket.GetBucketsParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation bucket.GetBuckets has not yet been implemented")
		}),
		ObjectGetObjectHandler: object.GetObjectHandlerFunc(func(params object.GetObjectParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation object.GetObject has not yet been implemented")
		}),
		ObjectinfoGetObjectInfoHandler: objectinfo.GetObjectInfoHandlerFunc(func(params objectinfo.GetObjectInfoParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation objectinfo.GetObjectInfo has not yet been implemented")
		}),
		ObjectsGetObjectsHandler: objects.GetObjectsHandlerFunc(func(params objects.GetObjectsParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation objects.GetObjects has not yet been implemented")
		}),

		// Applies when the "Authorization" header is set
		BearerAuth: func(token string) (*models.Principal, error) {
			return nil, errors.NotImplemented("api key auth (Bearer) Authorization from header param [Authorization] has not yet been implemented")
		},
		// default authorizer is authorized meaning no requests are blocked
		APIAuthorizer: security.Authorized(),
	}
}

/*StorageAPI the storage API */
type StorageAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator
	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator
	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer
	// MultipartformConsumer registers a consumer for the following mime types:
	//   - multipart/form-data
	MultipartformConsumer runtime.Consumer

	// BinProducer registers a producer for the following mime types:
	//   - application/octet-stream
	BinProducer runtime.Producer
	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// BearerAuth registers a function that takes a token and returns a principal
	// it performs authentication based on an api key Authorization provided in the header
	BearerAuth func(string) (*models.Principal, error)

	// APIAuthorizer provides access control (ACL/RBAC/ABAC) by providing access to the request and authenticated principal
	APIAuthorizer runtime.Authorizer

	// BucketAddBucketHandler sets the operation handler for the add bucket operation
	BucketAddBucketHandler bucket.AddBucketHandler
	// FileAddFileHandler sets the operation handler for the add file operation
	FileAddFileHandler file.AddFileHandler
	// ObjectAddObjectHandler sets the operation handler for the add object operation
	ObjectAddObjectHandler object.AddObjectHandler
	// BucketDeleteBucketHandler sets the operation handler for the delete bucket operation
	BucketDeleteBucketHandler bucket.DeleteBucketHandler
	// ObjectDeleteObjectHandler sets the operation handler for the delete object operation
	ObjectDeleteObjectHandler object.DeleteObjectHandler
	// ObjectsDeleteObjectsHandler sets the operation handler for the delete objects operation
	ObjectsDeleteObjectsHandler objects.DeleteObjectsHandler
	// BucketGetBucketsHandler sets the operation handler for the get buckets operation
	BucketGetBucketsHandler bucket.GetBucketsHandler
	// ObjectGetObjectHandler sets the operation handler for the get object operation
	ObjectGetObjectHandler object.GetObjectHandler
	// ObjectinfoGetObjectInfoHandler sets the operation handler for the get object info operation
	ObjectinfoGetObjectInfoHandler objectinfo.GetObjectInfoHandler
	// ObjectsGetObjectsHandler sets the operation handler for the get objects operation
	ObjectsGetObjectsHandler objects.GetObjectsHandler
	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// SetDefaultProduces sets the default produces media type
func (o *StorageAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *StorageAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *StorageAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *StorageAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *StorageAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *StorageAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *StorageAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the StorageAPI
func (o *StorageAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}
	if o.MultipartformConsumer == nil {
		unregistered = append(unregistered, "MultipartformConsumer")
	}

	if o.BinProducer == nil {
		unregistered = append(unregistered, "BinProducer")
	}
	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.BearerAuth == nil {
		unregistered = append(unregistered, "AuthorizationAuth")
	}

	if o.BucketAddBucketHandler == nil {
		unregistered = append(unregistered, "bucket.AddBucketHandler")
	}
	if o.FileAddFileHandler == nil {
		unregistered = append(unregistered, "file.AddFileHandler")
	}
	if o.ObjectAddObjectHandler == nil {
		unregistered = append(unregistered, "object.AddObjectHandler")
	}
	if o.BucketDeleteBucketHandler == nil {
		unregistered = append(unregistered, "bucket.DeleteBucketHandler")
	}
	if o.ObjectDeleteObjectHandler == nil {
		unregistered = append(unregistered, "object.DeleteObjectHandler")
	}
	if o.ObjectsDeleteObjectsHandler == nil {
		unregistered = append(unregistered, "objects.DeleteObjectsHandler")
	}
	if o.BucketGetBucketsHandler == nil {
		unregistered = append(unregistered, "bucket.GetBucketsHandler")
	}
	if o.ObjectGetObjectHandler == nil {
		unregistered = append(unregistered, "object.GetObjectHandler")
	}
	if o.ObjectinfoGetObjectInfoHandler == nil {
		unregistered = append(unregistered, "objectinfo.GetObjectInfoHandler")
	}
	if o.ObjectsGetObjectsHandler == nil {
		unregistered = append(unregistered, "objects.GetObjectsHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *StorageAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *StorageAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	result := make(map[string]runtime.Authenticator)
	for name := range schemes {
		switch name {
		case "Bearer":
			scheme := schemes[name]
			result[name] = o.APIKeyAuthenticator(scheme.Name, scheme.In, func(token string) (interface{}, error) {
				return o.BearerAuth(token)
			})

		}
	}
	return result
}

// Authorizer returns the registered authorizer
func (o *StorageAPI) Authorizer() runtime.Authorizer {
	return o.APIAuthorizer
}

// ConsumersFor gets the consumers for the specified media types.
// MIME type parameters are ignored here.
func (o *StorageAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONConsumer
		case "multipart/form-data":
			result["multipart/form-data"] = o.MultipartformConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result
}

// ProducersFor gets the producers for the specified media types.
// MIME type parameters are ignored here.
func (o *StorageAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/octet-stream":
			result["application/octet-stream"] = o.BinProducer
		case "application/json":
			result["application/json"] = o.JSONProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *StorageAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the storage API
func (o *StorageAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *StorageAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/bucket"] = bucket.NewAddBucket(o.context, o.BucketAddBucketHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/{bucketName}/file"] = file.NewAddFile(o.context, o.FileAddFileHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/{bucketName}/object"] = object.NewAddObject(o.context, o.ObjectAddObjectHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/bucket/{bucketName}"] = bucket.NewDeleteBucket(o.context, o.BucketDeleteBucketHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/{bucketName}/object"] = object.NewDeleteObject(o.context, o.ObjectDeleteObjectHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/{bucketName}/objects"] = objects.NewDeleteObjects(o.context, o.ObjectsDeleteObjectsHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/buckets"] = bucket.NewGetBuckets(o.context, o.BucketGetBucketsHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/{bucketName}/object"] = object.NewGetObject(o.context, o.ObjectGetObjectHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/{bucketName}/objectinfo"] = objectinfo.NewGetObjectInfo(o.context, o.ObjectinfoGetObjectInfoHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/{bucketName}/objects"] = objects.NewGetObjects(o.context, o.ObjectsGetObjectsHandler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *StorageAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *StorageAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *StorageAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *StorageAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *StorageAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[method][path] = builder(h)
	}
}
