// Code generated by go-swagger; DO NOT EDIT.

package object

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"platform/services/storage/models"
)

// AddObjectHandlerFunc turns a function with the right signature into a add object handler
type AddObjectHandlerFunc func(AddObjectParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn AddObjectHandlerFunc) Handle(params AddObjectParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// AddObjectHandler interface for that can handle valid add object params
type AddObjectHandler interface {
	Handle(AddObjectParams, *models.Principal) middleware.Responder
}

// NewAddObject creates a new http.Handler for the add object operation
func NewAddObject(ctx *middleware.Context, handler AddObjectHandler) *AddObject {
	return &AddObject{Context: ctx, Handler: handler}
}

/*AddObject swagger:route POST /{bucketName}/object object addObject

Add a new object into a bucket

*/
type AddObject struct {
	Context *middleware.Context
	Handler AddObjectHandler
}

func (o *AddObject) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAddObjectParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
