// Code generated by go-swagger; DO NOT EDIT.

package object

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"platform/services/storage/models"
)

// GetObjectOKCode is the HTTP code returned for type GetObjectOK
const GetObjectOKCode int = 200

/*GetObjectOK Ok

swagger:response getObjectOK
*/
type GetObjectOK struct {

	/*
	  In: Body
	*/
	Payload strfmt.Base64 `json:"body,omitempty"`
}

// NewGetObjectOK creates GetObjectOK with default headers values
func NewGetObjectOK() *GetObjectOK {

	return &GetObjectOK{}
}

// WithPayload adds the payload to the get object o k response
func (o *GetObjectOK) WithPayload(payload strfmt.Base64) *GetObjectOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get object o k response
func (o *GetObjectOK) SetPayload(payload strfmt.Base64) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetObjectOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetObjectBadRequestCode is the HTTP code returned for type GetObjectBadRequest
const GetObjectBadRequestCode int = 400

/*GetObjectBadRequest Bad request

swagger:response getObjectBadRequest
*/
type GetObjectBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetObjectBadRequest creates GetObjectBadRequest with default headers values
func NewGetObjectBadRequest() *GetObjectBadRequest {

	return &GetObjectBadRequest{}
}

// WithPayload adds the payload to the get object bad request response
func (o *GetObjectBadRequest) WithPayload(payload *models.APIResponse) *GetObjectBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get object bad request response
func (o *GetObjectBadRequest) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetObjectBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetObjectUnauthorizedCode is the HTTP code returned for type GetObjectUnauthorized
const GetObjectUnauthorizedCode int = 401

/*GetObjectUnauthorized Unauthorized

swagger:response getObjectUnauthorized
*/
type GetObjectUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetObjectUnauthorized creates GetObjectUnauthorized with default headers values
func NewGetObjectUnauthorized() *GetObjectUnauthorized {

	return &GetObjectUnauthorized{}
}

// WithPayload adds the payload to the get object unauthorized response
func (o *GetObjectUnauthorized) WithPayload(payload *models.APIResponse) *GetObjectUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get object unauthorized response
func (o *GetObjectUnauthorized) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetObjectUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetObjectNotFoundCode is the HTTP code returned for type GetObjectNotFound
const GetObjectNotFoundCode int = 404

/*GetObjectNotFound Not found

swagger:response getObjectNotFound
*/
type GetObjectNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetObjectNotFound creates GetObjectNotFound with default headers values
func NewGetObjectNotFound() *GetObjectNotFound {

	return &GetObjectNotFound{}
}

// WithPayload adds the payload to the get object not found response
func (o *GetObjectNotFound) WithPayload(payload *models.APIResponse) *GetObjectNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get object not found response
func (o *GetObjectNotFound) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetObjectNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetObjectInternalServerErrorCode is the HTTP code returned for type GetObjectInternalServerError
const GetObjectInternalServerErrorCode int = 500

/*GetObjectInternalServerError Internal error

swagger:response getObjectInternalServerError
*/
type GetObjectInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetObjectInternalServerError creates GetObjectInternalServerError with default headers values
func NewGetObjectInternalServerError() *GetObjectInternalServerError {

	return &GetObjectInternalServerError{}
}

// WithPayload adds the payload to the get object internal server error response
func (o *GetObjectInternalServerError) WithPayload(payload *models.APIResponse) *GetObjectInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get object internal server error response
func (o *GetObjectInternalServerError) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetObjectInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
